export const PAR_PUBLIC_VIEW = 'PAR_PUBLIC_VIEW';
export const PAR_PRESTATION_VIEW = 'PAR_PRESTATION_VIEW';

export const M52_INSTRUCTION = 'M52_INSTRUCTION';
export const AGGREGATED_INSTRUCTION = 'AGGREGATED_INSTRUCTION';