name: Build and Deploy
on: 
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - name: Test
        run: | 
          npm install
          npm test

  build-deploy-demo:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build-demo
      
      - name: Add and commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git add -f build/*
          git commit -m "build of repo at commit https://github.com/$GITHUB_REPOSITORY/tree/$GITHUB_SHA"

      - name: Deploy 🚀
        uses: ad-m/github-push-action@v0.6.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEPLOY_TARGET_BRANCH: gh-pages
          force: true